### 项目相关配置
##ruoyi:
##  # 名称
##  name: springboot2-dubbo-web
##  # 版本
##  version: 3.0.0
##  # 版权年份
##  copyrightYear: 2018
##  # 文件上传路径
##  profile: D:/profile/
##  # 获取ip地址开关
##  addressEnabled: true
#
## 开发环境配置
#server:
#  # 服务端口
#  port: 80
#  servlet:
#    # 项目contextPath
#    context-path: /bigstore
#  tomcat:
#    # tomcat的URI编码
#    uri-encoding: UTF-8
#    # tomcat最大线程数，默认为200
#    max-threads: 800
#    # Tomcat启动初始化的线程数，默认值25
#    min-spare-threads: 30
#
### 日志配置
##logging:
##  level:
##    com.ruoyi: debug
##    org.springframework: WARN
##    org.spring.springboot.dao: debug
#
## 用户配置
##user:
##  password:
##    # 密码错误{maxRetryCount}次锁定10分钟
##    maxRetryCount: 5
#
## Spring配置
#spring:
##  profiles:
##    active: druid
##  # 服务模块
##  devtools:
##    restart:
##      # 热部署开关
##      enabled: false
#  dubbo:
#      application:
#        name: bigstore-goods-con1
#      registry:
#        address: zookeeper://192.168.10.103:2181
#      protocol:
#        name: dubbo
#        prot: 20881
#
#
### Shiro
##shiro:
##  user:
##    # 登录地址
##    loginUrl: /login
##    # 权限认证失败地址
##    unauthorizedUrl: /unauth
##    # 首页地址
##    indexUrl: /index
##    # 验证码开关
##    captchaEnabled: false
##    # 验证码类型 math 数组计算 char 字符
##    captchaType: math
##  cookie:
##    # 设置Cookie的域名 默认空，即当前访问的域名
##    domain:
##    # 设置cookie的有效访问路径
##    path: /
##    # 设置HttpOnly属性
##    httpOnly: true
##    # 设置Cookie的过期时间，天为单位
##    maxAge: 30
##  session:
##    # Session超时时间（默认30分钟）
##    expireTime: 30
##    # 同步session到数据库的周期（默认1分钟）
##    dbSyncPeriod: 1
##    # 相隔多久检查一次session的有效性，默认就是10分钟
##    validationInterval: 10
#
### 防止XSS攻击
##xss:
##  # 过滤开关
##  enabled: true
##  # 排除链接（多个用逗号分隔）
##  excludes: /system/notice/*
##  # 匹配链接
##  urlPatterns: /system/*,/monitor/*,/tool/*
#
### 代码生成
##gen:
##  # 作者
##  author: ruoyi
##  # 默认生成包路径 module 需改成自己的模块名称 如 system monitor tool
##  packageName: com.ruoyi.module
##  # 自动去除表前缀，默认是true
##  autoRemovePre: true
##  # 表前缀(类名不会包含表前缀)
##  tablePrefix: sys_